### ISSUE TITLE
Using 'grant ref mod (x lsl 16)' as a slot id is risky

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-net-xen#14]
The grant refs are allocated from a kernel-wide space and are int32s but the slot ids are only int16s which must be unique within individual rings.

Although 64k grants is 256MiB of granted data (i.e. quite a lot) if multiple rings were active we could still get unlucky. Consider a single netfront instance with its two rings (RX and TX)

- netfront RX ring grants buffer space to the backend for receiving data
- not much data is received, so these requests are pending for quite a long time, meanwhile
- netfront TX ring is pumping data to the backend for transmission
- netfront RX ring receives a frame
- netfront RX allocates another gref for which `gref mod (1 lsl 16) = id` where `id` is already pending
- netfront RX ring receives a frame with the problematic `id`. It will find the most recent binding (via `Hashtbl.find`) in the `rx_map` `Hashtbl` which references the wrong page (the one we just added, presumably blank) and call the receive callback with it

**Comment by talex5** [comment]
Fixed by #28.
