### ISSUE TITLE
Possible race condition on startup

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-net-xen#20]
Got the following trace in synjitsu, where the initial ARP packet and the first SYNACK seems to somehow overlap, resulting in the SYNACK (`id=2`) never actually sent on the network.

```
ARP: sending gratuitous from 192.168.2.140
Netif.writev
Netif.writev_no_retry
Netif.write_already_locked
Netif.write_request id=1 available-devices: [0])
Netif.Share_page_pool.use
Netif.Shared_page_pool.alloc
Netif.write_request: id=1 len=42 size=42
Netif.notify
Netfi.write_already_locked: Front.push done
Manager: configuration done
FAST-START mode. Watching xenstore for incoming SYN!
Ports: 80
Dest-ip: 192.168.2.1
Dest-ports: 58195
Found 1 started connections.
tx=65535 sequence=-19772235 options=(SACK_ok(Timestamp 2112076375 0)Noop Noop(Window_size_shift 5)Noop(MSS 1460)) tx_isn=452894287 rx_wnd=65535 rx_wnd_sca=2
Found SYN cookies.
Segment.output time=0.17 xmit=true rexmit=true
Wire.xmit checksum=14b7 192.168.2.140.80->192.168.2.1.58195 rst=false syn=true fin=false psh=false seq=452894287 ack=4275195062 options=[ MSS=1460; Window>>2 ] datalen=0 datafrag=0 dataoff=7 olen=8
Netif.writev
Netif.writev_no_retry
Netif.write_already_locked
Netif.write_request id=2 available-devices: [0])
Netif.Share_page_pool.use
Netif.write_request: id=2 len=62 size=62
Netfi.write_already_locked: Front.push done
Netfif.poll_thread:loop
Netif.rx_poll
Netif.refill_requests
Netif.tx_poll
Netif.write_request: id=2 Lwt_ring.Front.write done!
Netif.Shared_page_pool.put
Netif.write_request: id=1 Lwt_ring.Front.write done!
Netif.Shared_page_pool.put
Netfif.poll_thread:loop
Netif.rx_poll
Netif.refill_requests
Netif.tx_poll
Netfif.poll_thread:loop
Netif.rx_poll
Netif.refill_requests
Netif.tx_poll
Netfif.poll_thread:loop
....
```

**Comment by samoht** [comment]
Note: this bugs is only present in 1.3.0, not in 1.2.0

**Comment by samoht** [comment]
We again met that bug in another stress tests. Would it be possible to (i) either revert the incriminated changesets (I'm not sure that's a good idea as these were supposed to fix an other real issue) and (ii) write unit-tests (if possible not involving setting a xen environment, but abstracting away some low-level stuff as @djs55 started to do it on other packages).

In a more general way, I think we should avoid as much as possible "pure" xen packages, without easy-to-deploy, runnable on unix, functional tests. These kinds of bugs are awful to track down so we should try to build as much as confidence as possible by other means.

**Comment by samoht** [comment]
See https://github.com/mirage/mirage-net-xen/commit/7d2777d789530e2104b6d9252cdca0d6f8078acb#commitcomment-9639114 and https://github.com/mirage/mirage-tcpip/issues/110

**Comment by djs55** [comment]
I've been working on removing the xen from mirage-net-xen, here is my progress so far:

In [djs55/ocaml-gnt]'s refactor-modules branch I have a new `MEMORY` signature which is abstract: https://github.com/djs55/ocaml-gnt/blob/refactor-modules/lib/s.mli#L17 and I have an implementation for Xen, in-process (in heap I called it) and Unix: https://github.com/djs55/ocaml-gnt/blob/refactor-modules/unix/unix_memory.ml

In [djs55/ocaml-evtchn]'s refactor-modules branch I have a new `EVENTS` signature: https://github.com/djs55/ocaml-evtchn/blob/refactor-modules/lib/s.mli#L17 which is implemented for Xen, in-process and Unix (sockets)

I've been going round and functorising things over these 2 signatures (typically plus a third, "CONFIGURATION" signature). This allows Unix tools to be created and little unit tests. This is all inspired by the similar work for vchan. I've functorised netfront (although I'm missing a few recent patches now) and am in the middle of writing netback, so I can have backend<->frontend tests.

Perhaps we should start accumulating test ideas in the issue tracker?

**Comment by samoht** [comment]
> Perhaps we should start accumulating test ideas in the issue tracker?

that would be great indeed! I really like to have a unix/in-memory implementation/simulations for `gnt` and `evntchn`. Would be great if you could document how to build "simple" unit-tests with them when you have time (or just give some examples).

A thing we should also do is make a quick pass at mirage's [TROVE](https://github.com/mirage/mirage-www/blob/master/TROVE) file and see which library don't have unit-tests and see if we can add them. A `mirage-lint` tool would be great for this ...

**Comment by MagnusS** [comment]
Here is another example of a unikernel that stops responding: https://gist.github.com/MagnusS/581280dde134aae05b2e

The unikernel connects to Netif and tries to send a single ARP query for 192.168.0.1. The code works fine in Virtualbox, but hangs on my cubieboard unless I uncomment the 1 sec sleep. When it hangs the ARP query is never transmitted on the bridge.

Working tcpdump output:
```
$ sudo tcpdump -ni br0 arp host 0.0.0.0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on br0, link-type EN10MB (Ethernet), capture size 65535 bytes
13:09:04.626383 ARP, Request who-has 192.168.0.1 (ff:ff:ff:ff:ff:ff) tell 0.0.0.0, length 28
13:09:04.627019 ARP, Reply 192.168.0.1 is-at 7c:4c:a5:d3:78:44, length 46
```
