### ISSUE TITLE
Parse error: [semi] expected after [str_item] (in [implem])

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-net-xen#32]
Got this strange error on a Travis build:

    #=== ERROR while installing mirage-net-xen.1.5.0 ==============================#
    # opam-version 1.2.2
    # os           linux
    # command      make
    # path         /home/travis/.opam/system/build/mirage-net-xen.1.5.0
    # compiler     system (4.02.3)
    # exit-code    2
    # env-file     /home/travis/.opam/system/build/mirage-net-xen.1.5.0/mirage-net-xen-10978-cbd16a.env
    # stdout-file  /home/travis/.opam/system/build/mirage-net-xen.1.5.0/mirage-net-xen-10978-cbd16a.out
    # stderr-file  /home/travis/.opam/system/build/mirage-net-xen.1.5.0/mirage-net-xen-10978-cbd16a.err
    ### stdout ###
    # [...]
    # /home/travis/.opam/system/bin/ocamlfind ocamldep -package cstruct -syntax camlp4o -package cstruct.syntax -package ipaddr -syntax camlp4o -package lwt.syntax -package mirage-profile -package mirage-xen -package result -package xen-evtchn -package xen-gnt -modules lib/frontend.mli > lib/frontend.mli.depends
    # /home/travis/.opam/system/bin/ocamlfind ocamldep -package cstruct -syntax camlp4o -package cstruct.syntax -package ipaddr -syntax camlp4o -package lwt.syntax -package mirage-profile -package mirage-xen -package result -package xen-evtchn -package xen-gnt -modules lib/s.ml > lib/s.ml.depends
    # + /home/travis/.opam/system/bin/ocamlfind ocamldep -package cstruct -syntax camlp4o -package cstruct.syntax -package ipaddr -syntax camlp4o -package lwt.syntax -package mirage-profile -package mirage-xen -package result -package xen-evtchn -package xen-gnt -modules lib/s.ml > lib/s.ml.depends
    # File "lib/s.ml", line 21, characters 0-1:
    # Parse error: [semi] expected after [str_item] (in [implem])
    # File "lib/s.ml", line 1:
    # Error: Error while running external preprocessor
    # Command line: camlp4 '-I' '/usr/lib/ocaml/camlp4' '-I' '/home/travis/.opam/system/lib/cstruct' '-I' '/home/travis/.opam/system/lib/lwt' '-I' '/home/travis/.opam/system/lib/lwt' '-parser' 'o' '-parser' 'op' '-printer' 'p' 'cstruct-syntax.cma' 'lwt-syntax-options.cma' 'lwt-syntax.cma'  'lib/s.ml' > /tmp/ocamlppe2002e
    # 
    # Command exited with code 2.
    ### stderr ###
    # W: Cannot find source file matching module 'netchannel' in library netchannel
    # E: Failure("Command ''/usr/bin/ocamlbuild' lib/netchannel.cma lib/netchannel.cmxa lib/netchannel.a lib/netchannel.cmxs compat/mirage-net-xen.cma compat/mirage-net-xen.cmxa compat/mirage-net-xen.a compat/mirage-net-xen.cmxs -tag debug' terminated with error code 10")
    # make: *** [build] Error 1

**Comment by samoht** [comment]
That's a missing sexplib constraint. I'll add this.

**Comment by samoht** [comment]
Fixed by #33 and https://github.com/ocaml/opam-repository/pull/5808
