### ISSUE TITLE
unikernels built with mirage-net-xen version 1.12.0 can't be linked by mirage 3.5.0

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-net-xen#93]
When attempting to link the unikernel, `libxenbindings.a` can't be found.  I'll try to reproduce this on a machine where I can more easily capture an error log to paste here.

**Comment by avsm** [comment]
there should be a constraint on mirage-xen.4.0.0, which in turn should have the latest mirage-minios-xen i think

**Comment by hannesm** [comment]
A year later, with mirage 3.8.0 released, is this still an issue? I can see mirage-xen < 4.0.0 in mirage-net-xen 1.11.0, >= 4.0.0 & < 5.0.0 in mirage-net-xen 1.12.0 and >= 5.0.0 in 1.13.0. If this is still an issue, please reopen with a more complete opam package universe that fails. Thanks.
